修改健康检查starter名字
sofastack/sofastack.tech pull request #1250
Opened 2024-02-23 02:00 UTC by wangchengming666

修改健康检查starter名字，老版本名字已经更改，新版本是sofa-boot-actuator

2024-02-23 02:15 UTC, HzjNeverStop requested changes

2024-02-23 02:15 UTC, HzjNeverStop commented on content/zh/projects/sofa-boot/dependency-management/index.md
> +|健康检查|sofa-boot-actuator|
换成 actuator-sofa-boot-starter

2024-02-23 02:16 UTC, wangchengming666 commented on content/zh/projects/sofa-boot/dependency-management/index.md
> +|健康检查|sofa-boot-actuator|
> 换成 actuator-sofa-boot-starter

down

2024-02-23 02:19 UTC, HzjNeverStop approved these changes
LGTM

2024-02-23 02:19 UTC, HzjNeverStop approved these changes
LGTM

2024-02-23 02:19 UTC, HzjNeverStop approved these changes
LGTM

2024-02-26 02:21 UTC, nobodyiam approved these changes
LGTM

2024-02-26 02:21 UTC, merged