SOFAArk 动态部署源码解析
sofastack/sofastack.tech pull request #970
Opened 2022-07-19 03:39 UTC by it-linnan

2022-08-03 09:51 UTC, yuanyuancin commented on content/zh/projects/sofa-boot/sofa-ark-dynamic-deploy/index.md
> +1. 将当前 ClassLoader 设置为 BizModel 的 ClassLoader，并暂存原 ClassLoader
当前 ClassLoader 建议写成 “当前线程上下文 ClassLoader”，避免和加载当前类的 classloader 歧义

2022-08-03 09:51 UTC, yuanyuancin commented on content/zh/projects/sofa-boot/sofa-ark-dynamic-deploy/index.md
> +
在 sofaRuntimeManager.shutDownExternally(); 中会关闭 master biz 的 spring 上下文

2022-08-12 02:44 UTC, yuanyuancin approved these changes
LGFM

2022-08-12 02:44 UTC, yuanyuancin approved these changes

2022-08-12 03:23 UTC, seeflood requested changes

2022-08-12 03:23 UTC, seeflood commented on content/zh/projects/sofa-boot/sofa-ark-dynamic-deploy/index.md
> +tags: [“源码解析”]
```suggestion
tags: ["源码解析"]
```

2022-08-12 03:33 UTC, seeflood approved these changes

2022-08-12 03:34 UTC, merged

2022-08-12 03:34 UTC, seeflood commented
Thanks for your contribution!